### ISSUE TITLE
Version1 테스트 

### ISSUE THREAD

**Issue by Seunghui98** [Eye-Remocon/Face_Recognition#1]
README.md 따라서 파이썬 설치, 필요 패키지 설치 후에 테스트 해주세요.
Window에서 패키지 설치가 많이 까다로울 수도 있기 때문에 시간 여유가 있으시다면 리눅스 환경에서 하시는 걸 추천드립니다.
하다가 오류나거나 이해 안가시는 부분 있으시다면 comment 부탁드려요 ^^

**Comment by smarthome-hanium** [comment]
@Seunghui98 @lspc678 코드 공유 감사합니다. 우리 프로젝트는 컨테이너를 베이스로 동작되니 윈도우즈는 고려치말고 Ubuntu, Raspberry Pi OS를 대상으로 구현 및 테스트 부탁드려요.
